# SPDX-FileCopyrightText: (C) 2022 Avnet Embedded GmbH
# SPDX-License-Identifier: GPL-3.0-only

name: Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  auto_merge:
    if: github.event.pull_request.user.login != 'dependabot[bot]'
    runs-on: ubuntu-latest
    name: auto_merge
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4.0.0
        name: auto_approve
        if: |
          contains(toJson(github.event.pull_request.labels.*.name), 'automerge')
        with:
          github-token: ${{ secrets.DISPATCH_PAT }}
      - uses: "pascalgn/automerge-action@v0.16.4"
        name: auto_merge
        env:
          GITHUB_TOKEN: "${{ secrets.DISPATCH_PAT }}"
          MERGE_LABELS: "automerge"
          UPDATE_LABELS: "automerge"
          MERGE_METHOD: "rebase"
          MERGE_DELETE_BRANCH: true
          MERGE_FORKS: false
          MERGE_RETRIES: "20"
          MERGE_RETRY_SLEEP: "15000"
